name: st_env_10_04
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - astunparse=1.6.3=py_0
  - atk-1.0=2.36.0=ha1a6a79_0
  - beautifulsoup4=4.12.2=py310h06a4308_0
  - blas=1.0=mkl
  - boltons=23.0.0=py310h06a4308_0
  - boost-cpp=1.73.0=h7f8727e_12
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.19.0=h5eee18b_0
  - ca-certificates=2023.08.22=h06a4308_0
  - cairo=1.16.0=hb05425b_5
  - certifi=2023.7.22=py310h06a4308_0
  - chardet=4.0.0=py310h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py310h06a4308_0
  - cmake=3.26.4=h96355d8_0
  - conda-content-trust=0.1.3=py310h06a4308_0
  - conda-package-handling=2.1.0=py310h06a4308_0
  - conda-package-streaming=0.8.0=py310h06a4308_0
  - cryptography=39.0.1=py310h9ce1e76_2
  - dataclasses=0.8=pyh6d0b6a4_7
  - expat=2.5.0=h6a678d5_0
  - filelock=3.9.0=py310h06a4308_0
  - fmt=10.1.1=h00ab1b0_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - future=0.18.3=py310h06a4308_0
  - gdk-pixbuf=2.42.10=h5eee18b_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.69.1=he621ea3_2
  - gobject-introspection=1.72.0=py310hbb6d50b_2
  - graphite2=1.3.14=h295c915_1
  - graphviz=2.50.0=h1b29801_1
  - gtk2=2.24.33=h73c1081_2
  - gts=0.7.6=hb67d8dd_3
  - harfbuzz=4.3.0=hf52aaf7_1
  - icu=58.2=he6710b0_3
  - idna=3.4=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jpeg=9e=h5eee18b_1
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libaio=0.3.113=h5eee18b_0
  - libarchive=3.6.2=h6ac8c49_2
  - libboost=1.73.0=h28710b8_12
  - libcurl=8.2.1=h251f7ec_0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20221030=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_2
  - libgd=2.3.3=h695aa2c_1
  - libiconv=1.16=h7f8727e_2
  - liblief=0.12.3=h6a678d5_0
  - libllvm14=14.0.6=hdb19cb5_3
  - libmamba=1.5.1=h744094f_0
  - libmambapy=1.5.1=py310h39ff949_0
  - libnghttp2=1.52.0=h2d74bed_1
  - libpng=1.6.39=h5eee18b_0
  - librsvg=2.54.4=h36cc946_3
  - libsolv=0.7.25=hfc55251_0
  - libssh2=1.10.0=hdbd6064_2
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.5.1=h6a678d5_0
  - libtool=2.4.6=h6a678d5_1009
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.44.2=h5eee18b_0
  - libwebp=1.3.2=h11a3e52_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.10.3=hcbfbd50_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_0
  - magma-cuda118=2.6.1=1
  - markupsafe=2.1.1=py310h7f8727e_0
  - mkl=2023.1.0=h213fc3f_46343
  - mkl-include=2023.1.0=h06a4308_46343
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.8=py310h5eee18b_0
  - mkl_random=1.2.4=py310hdb19cb5_0
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - ncurses=6.4=h6a678d5_0
  - ninja-base=1.10.2=hd09550d_5
  - nspr=4.35=h6a678d5_0
  - nss=3.89.1=h6a678d5_0
  - numpy=1.24.3=py310h5f9d8c6_1
  - numpy-base=1.24.3=py310hb5e798b_1
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=3.1.3=hd590300_0
  - pango=1.50.7=h05da053_0
  - patch=2.7.6=h7b6447c_1001
  - patchelf=0.17.2=h6a678d5_0
  - pcre=8.45=h295c915_0
  - pcre2=10.37=he7ceb23_1
  - pip=23.2.1=py310h06a4308_0
  - pixman=0.40.0=h7f8727e_1
  - pkginfo=1.9.6=py310h06a4308_0
  - pluggy=1.0.0=py310h06a4308_1
  - poppler=22.12.0=h381b16e_0
  - poppler-data=0.4.11=h06a4308_1
  - py-lief=0.12.3=py310h6a678d5_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.4=py310h5eee18b_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pymongo=3.12.0=py310h295c915_0
  - pyopenssl=23.0.0=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.12=h955ad1f_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - python_abi=3.10=2_cp310
  - pytz=2023.3.post1=py310h06a4308_0
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h295c915_1
  - reproc-cpp=14.2.4=h295c915_1
  - requests=2.31.0=py310h06a4308_0
  - rhash=1.4.3=hdbd6064_0
  - ruamel.yaml=0.17.21=py310h5eee18b_0
  - ruamel.yaml.clib=0.2.6=py310h5eee18b_1
  - setuptools=68.0.0=py310h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - soupsieve=2.5=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py310h06a4308_0
  - toolz=0.12.0=py310h06a4308_0
  - tqdm=4.65.0=py310h2f386ee_0
  - unzip=6.0=h611a1e1_0
  - urllib3=1.26.16=py310h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - yaml=0.2.5=h7b6447c_0
  - yaml-cpp=0.7.0=h295c915_1
  - zip=3.0=h7f8727e_1
  - zlib=1.2.13=hd590300_5
  - zstandard=0.19.0=py310h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - about-time==4.2.1
      - absl-py==1.4.0
      - accelerate==0.23.0
      - aim==4.0.3
      - aim-ui==4.0.3
      - aimrocks==0.5.1
      - aiohttp==3.8.5
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.1
      - alembic==1.12.0
      - alive-progress==3.1.4
      - antlr4-python3-runtime==4.9.3
      - anyio==3.7.1
      - apex==0.1
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - array-record==0.4.1
      - arrow==1.3.0
      - arviz==0.16.1
      - asgiref==3.7.2
      - asttokens==2.4.0
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - autograd==1.6.2
      - babel==2.13.0
      - backcall==0.2.0
      - backoff==2.2.1
      - bleach==6.1.0
      - blessed==1.20.0
      - bokeh==3.2.2
      - boto3==1.28.60
      - botocore==1.31.60
      - branca==0.6.0
      - cachetools==5.3.1
      - cdsapi==0.6.1
      - celerite==0.4.2
      - cffi==1.16.0
      - cfgrib==0.9.10.4
      - cftime==1.6.2
      - chex==0.1.83
      - climetlab==0.17.8
      - cloudpickle==2.2.1
      - cma==3.2.2
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorful==0.5.5
      - colorlog==6.7.0
      - comm==0.1.4
      - configspace==0.7.1
      - contextlib2==21.6.0
      - contourpy==1.1.1
      - copulas==0.9.1
      - ctgan==0.7.4
      - cupy-cuda11x==12.2.0
      - cycler==0.12.0
      - cython==3.0.2
      - dask==2023.9.3
      - datasets==2.14.5
      - debugpy==1.8.0
      - decorator==5.1.1
      - deepecho==0.4.2
      - deephyper==0.6.0
      - deepspeed==0.10.3+04a6fedf
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dill==0.3.7
      - distlib==0.3.7
      - django==4.2.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - eccodes==1.6.1
      - ecmwf-api-client==1.6.3
      - ecmwf-opendata==0.2.0
      - ecmwflibs==0.5.3
      - entrypoints==0.4
      - etils==1.5.0
      - evaluate==0.4.0
      - exceptiongroup==1.1.3
      - executing==2.0.0
      - faker==14.2.1
      - fastapi==0.103.2
      - fastjsonschema==2.18.1
      - fastprogress==1.0.3
      - fastrlock==0.8.2
      - findlibs==0.0.5
      - flatbuffers==23.5.26
      - flax==0.7.4
      - fonttools==4.43.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gast==0.4.0
      - gensim==4.3.2
      - gitdb==4.0.10
      - gitpython==3.1.37
      - google-api-core==2.12.0
      - google-auth==2.23.2
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.60.0
      - gpustat==1.1.1
      - gpytorch==1.11
      - grapheme==0.6.0
      - greenlet==3.0.0
      - grpcio==1.59.0
      - gviz-api==1.10.0
      - h11==0.14.0
      - h5netcdf==1.2.0
      - h5py==3.9.0
      - hiredis==2.2.3
      - hjson==3.1.0
      - horovod==0.28.1
      - huggingface-hub==0.16.4
      - humanfriendly==10.0
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - imageio==2.31.5
      - importlib-metadata==6.8.0
      - importlib-resources==6.1.0
      - iniconfig==2.0.0
      - ipykernel==6.25.2
      - ipython==8.16.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jax==0.4.17
      - jaxlib==0.4.17+cuda11.cudnn86
      - jaxtyping==0.2.22
      - jedi==0.19.1
      - jinja2==3.0.3
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpickle==3.0.2
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - jupyter==1.0.0
      - jupyter-client==8.4.0
      - jupyter-console==6.6.3
      - jupyter-core==5.4.0
      - jupyter-events==0.7.0
      - jupyter-lsp==2.2.0
      - jupyter-server==2.7.3
      - jupyter-server-terminals==0.4.4
      - jupyterlab==4.0.6
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.25.0
      - jupyterlab-widgets==3.0.9
      - keras==2.13.1
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - khash==0.5.0a5
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - libclang==16.0.6
      - libensemble==1.0.0
      - lightning-utilities==0.9.0
      - line-profiler==4.1.1
      - linear-operator==0.5.2
      - llvmlite==0.41.0
      - locket==1.0.0
      - magics==1.5.8
      - mako==1.2.4
      - markdown==3.4.4
      - markdown-it-py==3.0.0
      - matplotlib==3.8.0
      - matplotlib-inline==0.1.6
      - matplotx==0.3.10
      - mdurl==0.1.2
      - megatron-core==0.2.0
      - mistune==3.0.2
      - ml-collections==0.1.1
      - ml-dtypes==0.3.1
      - mock==5.1.0
      - monotonic==1.6
      - mpi4jax==0.3.15.post1
      - mpi4py==3.1.5
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multipledispatch==1.0.0
      - multiprocess==0.70.15
      - multiurl==0.2.1
      - munch==2.5.0
      - nbclient==0.8.0
      - nbconvert==7.9.2
      - nbformat==5.9.2
      - nest-asyncio==1.5.8
      - netcdf4==1.6.4
      - networkx==3.1
      - ninja==1.11.1
      - nodeenv==1.8.0
      - notebook==7.0.4
      - notebook-shim==0.2.3
      - numba==0.58.0
      - numpngw==0.1.3
      - numpyro==0.13.2
      - nvidia-ml-py==12.535.108
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnx==1.14.1
      - onnx-tf==1.10.0
      - onnxruntime-gpu==1.16.0
      - opencensus==0.11.3
      - opencensus-context==0.1.3
      - opencv-python-headless==4.8.1.78
      - opt-einsum==3.3.0
      - optax==0.1.7
      - orbax-checkpoint==0.4.1
      - overrides==7.4.0
      - packaging==23.2
      - pandas==2.1.1
      - pandocfilters==1.5.0
      - parse==1.19.1
      - parso==0.8.3
      - partd==1.4.1
      - pathtools==0.1.2
      - pdbufr==0.11.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.1
      - platformdirs==3.11.0
      - plotly==5.17.0
      - portpicker==1.6.0
      - prometheus-client==0.17.1
      - promise==2.3
      - prompt-toolkit==3.0.39
      - protobuf==3.20.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - py-spy==0.3.14
      - py4j==0.10.9.7
      - pyarrow==13.0.0
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybind11==2.11.1
      - pycuda==2022.2.2
      - pydantic==1.10.13
      - pydot==1.4.2
      - pyg-lib==0.2.0
      - pygments==2.16.1
      - pymoo==0.6.0.1
      - pyodc==1.3.0
      - pyparsing==3.1.1
      - pyright==1.1.329
      - pytest==7.4.2
      - python-dateutil==2.8.2
      - python-graphviz==0.20.1
      - python-json-logger==2.0.7
      - pytools==2023.1.1
      - pytorch-lightning==2.0.9.post0
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - ray==2.7.0
      - rdkit-pypi==2022.9.5
      - rdt==1.7.0
      - redis==5.0.1
      - referencing==0.30.2
      - regex==2023.10.3
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - restrictedpython==6.2
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.6.0
      - rpds-py==0.10.3
      - rsa==4.9
      - s3transfer==0.7.0
      - sacred==0.8.4
      - safetensors==0.3.3
      - scikit-image==0.22.0
      - scikit-learn==1.3.1
      - scipy==1.11.3
      - sdmetrics==0.11.1
      - sdv==1.4.0
      - seaborn==0.13.0
      - segment-analytics-python==2.2.3
      - send2trash==1.8.2
      - sentry-sdk==1.31.0
      - setproctitle==1.3.3
      - smart-open==6.4.0
      - smilespe==0.0.3
      - smmap==5.0.1
      - sniffio==1.3.0
      - sqlalchemy==2.0.21
      - sqlparse==0.4.4
      - stack-data==0.6.3
      - starlette==0.27.0
      - sympy==1.12
      - tabulate==0.9.0
      - tenacity==8.2.3
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorboard-plugin-profile==2.14.0
      - tensorflow==2.13.0
      - tensorflow-addons==0.21.0
      - tensorflow-datasets==4.9.3
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-metadata==1.14.0
      - tensorflow-probability==0.21.0
      - tensorstore==0.1.45
      - termcolor==2.3.0
      - terminado==0.17.1
      - tf2onnx==1.15.1
      - threadpoolctl==3.2.0
      - tifffile==2023.9.26
      - timm==0.9.7
      - tinycss2==1.2.1
      - tokenizers==0.14.0
      - toml==0.10.2
      - torch==2.0.1
      - torch-cluster==1.6.1
      - torch-geometric==2.3.1
      - torch-scatter==2.1.1
      - torch-sparse==0.6.17
      - torch-spline-conv==1.2.2+pt20cu118
      - torch-tb-profiler==0.4.1
      - torchinfo==1.8.0
      - torchmetrics==1.2.0
      - torchvision==0.15.2a0+fa99a53
      - torchviz==0.0.2
      - tornado==6.3.3
      - traitlets==5.11.2
      - transformers==4.34.0
      - triton==2.1.0
      - typeguard==2.13.3
      - types-python-dateutil==2.8.19.14
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - uri-template==1.3.0
      - uvicorn==0.23.2
      - virtualenv==20.21.0
      - wandb==0.15.12
      - watchdog==3.0.0
      - wcwidth==0.2.8
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.6.4
      - websockets==11.0.3
      - werkzeug==3.0.0
      - wheel==0.41.2
      - widgetsnbextension==4.0.9
      - wrapt==1.15.0
      - xarray==2023.9.0
      - xarray-einstats==0.6.0
      - xformers==0.0.22
      - xgboost==2.0.0
      - xxhash==3.3.0
      - xyzservices==2023.7.0
      - yarl==1.9.2
      - zipp==3.17.0
